services:
  dind-daemon:
    image: "docker:dind-rootless"
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      "dind-network":
        aliases:
          - "docker"
    privileged: true
  dind-client:
    image: "docker:latest"
    environment:
      DOCKER_HOST: "tcp://docker:2375"
      SSH_AUTH_SOCK: "/root/.ssh/agent"
    command: sh -c 'while [ 1 ]; do sleep 1000; done'
    volumes:
      - $SSH_AUTH_SOCK:/root/.ssh/agent
    depends_on:
      - "dind-daemon"
    networks:
      "dind-network": {}

networks:
  "dind-network":
    name: "dind-network"
